### ISSUE TITLE
Win7 Compatibility

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [YourKalamity/lazy-dsi-file-downloader#16]
does not work on win7... can that be fixed?

**Comment by YourKalamity** [comment]
It should work, could you show me the error you see when launching the file from a command prompt?

1. Press Win + R
2. Type `cmd` and hit `Enter` in the Run Window
3. `cd` into the folder you downloaded the file to, type the file name and hit enter to run the program
4. Copy any errors into a reply to this thread

**Comment by MyTDT-Mysoft** [comment]
well actually the error is a messagebox so...
![image](https://user-images.githubusercontent.com/16870416/145839930-a4c05cf3-dc61-47c4-ae09-38ec2072076a.png)

do i lack something required? that dependency isnt directly from the .exe so i assume its either packed or extract & run something... unless that is from the C runtime...

**Comment by YourKalamity** [comment]
This seems to be an issue with running the application on Windows 7 since Python dropped support for it with version 3.9
I'll try compiling the next release with python 3.8 instead since that should still be supported

In the meantime, Windows 7 users are advised to use the python version with 3.5+ (up to 3.8)

**Comment by YourKalamity** [comment]
Should be fixed with c07d16e91f5d4656452f1e37119e786ae6456ac6
