### ISSUE TITLE
[BUG] - Stuck after "TWiLight Menu ++ Extracted"

### ISSUE THREAD

**Issue by turbocomppro** [YourKalamity/lazy-dsi-file-downloader#20]
**Describe the bug**
Program seems to be stuck after "TWiLight Menu ++ Extracted"

**To Reproduce**
1. Open program (lazy-dsi-file-downloader-v3.2.2-Windows.exe)
2. Click on 'Next', 'Next', 'Next'
3. Select 'Click to select folder', (select where my SD card is), Click 'Start'
5.  Terminal message:
Downloading Memory Pit
Memory Pit Downloaded
Downloading TWiLight Menu ++
TWiLight Menu ++ Downloaded
TWiLight Menu ++ Extracted

Nothing happens after this. Waited 10+ minutes. All buttons are grayed out.

**Expected behavior**
No idea but maybe the 'Finish' buttons lights up and work?  No idea if all needed files have been downloaded.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Tried with 2 different SD cards. Also tried with Run as Administrator.

**Comment by YourKalamity** [comment]
Unsure why exactly this has been occurring, this seems to be an issue that randomly affects some systems, I have been trying to replicate the problem on my side, but it doesn't occur

**Comment by weirdeetz** [comment]
Hi,
Have the same problem here.
Mine is stop at "Downloading dumpTool"

Downloading Memory Pit
Memory Pit Downloaded
Downloading TWiLight Menu ++
TWiLight Menu ++ Downloaded
TWiLight Menu ++ Extracted
TWiLight Menu ++ placed on SD card
Downloading DeadSkullzJr's Cheat database
DeadSkullzJr's Cheat Database downloaded
Downloading dumpTool

I thought it was because the file is too large to download, but after check the dupTool.nds is only a 218kb file.

I'm using Mac OSX 12.4 Monterey anyway.

Thanks,

**Comment by exurd** [comment]
This occurred with me as well on the Windows version. I switched to the python version and got this error:
```FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'E:/hiya/'```
I think it's trying to create already existing folders and halts the entire program if it fails.

**Comment by YourKalamity** [comment]
Thank you for this @exurd , I believe that was the issue.
This should be fixed with a233bd8a27ecc143eebe98b7df1163957e122e85
